name: Export Packwiz

on:
  push:
    branches:
      - master

jobs:
  packwiz-export:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Install mcman
      run: |
        sudo curl -L -o /usr/bin/mcman https://github.com/ParadigmMC/mcman/releases/latest/download/mcman
        sudo chmod +x /usr/bin/mcman

    - name: Run mcman export packwiz
      run: mcman export packwiz
      env:
        MODPACK_VERSION: ${{ github.sha }}

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update packwiz pack
